version: 2

jobs:
  unit_tests:
    docker:
      - image: circleci/node:10.17.0
    steps:
      - checkout
      - run:
          name: "Install node dependencies"
          command: yarn
      - run:
          name: "Jest Test Suite"
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "packages/client/reports/junit"
            JEST_JUNIT_OUTPUT_NAME: "jest-test-results.xml"
      - run:
          name: "Send test coverage to Codacy"
          command: cat ./packages/client/coverage/lcov.info | node_modules/.bin/codacy-coverage --language typescript
      - store_test_results:
          path: packages/client/reports
      - store_artifacts:
          name: "Uploading JUnit artifacts"
          path: packages/client/reports/junit
      - store_artifacts:
          name: "Uploading code coverage artifacts"
          path: packages/client/coverage
  eslint:
    docker:
      - image: circleci/node:10.17.0
    steps:
      - checkout
      - run:
          name: "Install node dependencies"
          command: yarn
      - run:
          name: "Run ESlint"
          command: yarn lint:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "packages/client/reports/junit"
            JEST_JUNIT_OUTPUT_NAME: "jest-test-results.xml"
      - store_test_results:
          path: packages/client/reports
      - store_artifacts:
          name: "Uploading JUnit artifacts"
          path: packages/client/reports/junit
  e2e:
    docker:
      - image: circleci/node:10.17.0-browsers
        environment:
          TS_NODE_PROJECT: tsconfig.json
          SELENIUM_BROWSER: "chrome"
    steps:
      - checkout
      - run:
          name: "Install node dependencies"
          command: yarn
      - run:
          name: Prepare Environment variables
          command: TARGET_ENV=STAGE bash packages/client/scripts/create-env.sh
      - run:
          name: Host website
          command: yarn serve
          background: true
      - run:
          name: Wait for a ready environment
          command: bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done'
      - run:
          name: Run E2E
          command: yarn e2e
      - run:
          name: Generates HTML report from the JSON generated by CucumberJS
          command: yarn e2e:report
      - store_artifacts:
          name: Store JSON artifacts
          path: packages/e2e/reporting/json
      - store_artifacts:
          name: Store HTML artifacts
          path: packages/e2e/reporting/html

workflows:
  version: 2
  ci:
    jobs:
      - eslint
      - unit_tests
      - e2e:
          requires:
            - eslint
            - unit_tests
