version: 2

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:10
        environment:
          TS_NODE_PROJECT: e2e/tsconfig.json
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package-lock.json" }}
          - npm-dependencies-
      - run:
          name: "Install node dependencies"
          command: npm ci
      - save_cache:
          name: Caching node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  unit_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restoring node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: "Jest Test Suite"
          command: npm run test:ci -- --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit"
            JEST_JUNIT_OUTPUT_NAME: "jest-test-results.xml"
      - store_test_results:
          path: reports
      - store_artifacts:
          name: "Uploading JUnit artifacts"
          path: reports/junit
      - store_artifacts:
          name: "Uploading code coverage artifacts"
          path: coverage
  eslint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restoring node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: "Run ESlint"
          command: ./node_modules/.bin/eslint --format junit -o reports/junit/js-lint-results.xml --ext=ts,tsx src/**/*
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit"
            JEST_JUNIT_OUTPUT_NAME: "jest-test-results.xml"
      - store_test_results:
          path: reports
      - store_artifacts:
          name: "Uploading JUnit artifacts"
          path: reports/junit
  e2e:
    docker:
      - image: circleci/node:jessie-browsers
        environment:
          TS_NODE_PROJECT: "e2e/tsconfig.json"
          SELENIUM_BROWSER: "chrome"
    steps:
      - checkout

      - restore_cache:
          name: Restoring node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Prepare Environment variables
          command: bash scripts/create-env.sh

      - run:
          name: Host website
          command: npm run serve

      - run:
          name: Run E2E
          command: npm run e2e

      - run:
          name: Generates HTML report from the JSON generated by cucumberjs
          command: npm run e2e-report

      - store_artifacts:
          name: Store JSON artifacts
          path: e2e/reporting/json

      - store_artifacts:
          name: Store HTML artifacts
          path: e2e/reporting/html


workflows:
  version: 2
  ci:
    jobs:
      - install_dependencies
      - eslint:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
      - e2e:
          requires:
              - unit_tests
              - eslint
