export const useNewGame = jest.fn(() => ({
  steps: ['first', 'second'],
  rules: {},
  setup: {},
  teamColors: [],
  teams: 1,
  colorsList: [],
  error: false,
  checkStep: jest.fn(),
  activeStep: 0,
  completedSteps: [],
  getValidationNotes: jest.fn(),
  gameSubmitted: false,
  onSetStep: jest.fn(),
  onTeamsChange: jest.fn(),
  onGameNameChange: jest.fn(),
  onTeamColorsChange: jest.fn(),
  onGameRulesChange: jest.fn(),
  onPredefinedGameRuleChange: jest.fn(),
}));
